import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import RootProvider from "@/components/providers/RootProvider";
import Toast from "@/components/ui/toast";
import { http } from "@/helpers/http";
import { cookies } from "next/headers";
import { VendorProfile } from "@/types";
import { Suspense } from "react";
import { StaticHero } from "@/components/StaticHero";
import { SigninForm } from "@/components/SigninForm";
import { VendorProfileCompletion } from "@/components/VendorProfileCompletion";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookiestore = await cookies();
	const accessToken = cookiestore.get("accessToken")?.value;
	let vendorProfile: VendorProfile | null = null;

	try {
		const data: VendorProfile = await http.get("/vendor/profile", {
			headers: {
				Authorization: `Bearer ${accessToken}`,
			},
		});
		vendorProfile = data;
		//console.log(data);
	} catch (error) {
		console.log(error);
	}

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<RootProvider>
					<Toast />
					{vendorProfile &&
					vendorProfile.businessName &&
					vendorProfile.address ? (
						children
					) : (
						<Suspense>
							<div className="flex h-screen overflow-hidden bg-gray-50">
								<StaticHero />
								<VendorProfileCompletion />
							</div>
						</Suspense>
					)}
				</RootProvider>
			</body>
		</html>
	);
}
